#!/bin/bash

cd /home/ben/Animal-Record-Keeping/

#source /home/ben/.rvm/scripts/rvm
. /home/ben/.rvm/environments/ruby-1.8.7-head

rake populate_census_entries RAILS_ENV=production
echo "task-census entries populated"
