#!/bin/bash
set +e

cd /home/ben/Animal-Record-Keeping/

#source /home/ben/.rvm/scripts/rvm
. /home/ben/.rvm/environments/ruby-1.8.7-head

echo "checking tasks due today"
rake email_if_tasks_not_done RAILS_ENV=production
echo "tasks due today checked"
