#!/bin/bash
set +e

cd /home/ben/Animal-Record-Keeping/

#source /home/ben/.rvm/scripts/rvm
. /home/ben/.rvm/environments/ruby-1.8.7-head

echo "populating automatic flight logs"
rake populate_daily_flight_logs RAILS_ENV=production
echo "automatic flight logs populated"
